baseURL = 'https://stefanogabryel.it/'
languageCode = 'it-IT'
title = 'Fotografo per Hotel, B&B e Agriturismi in Toscana'
theme = "napoli"

[pagination]
  pagerSize = 500

[permalinks]
  posts = "/blog/:slug/"

[params]
    # footer infos
    piva = "02089670471"
    iban = "IT17B3609201600524148650894"

    # contacts
    instagramLink = "https://www.instagram.com/stefanogfotografia/"
    whatsappLink = "https://wa.me/message/T4667RVAVPEJB1"
    email = "mailto:stefano.gabryel@gmail.com"
    phone = "tel:+393513663017"


[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3


[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

[outputFormats]
  [outputFormats.LLM]
    mediaType = "text/plain"
    baseName = "llms"
    isPlainText = true

[outputs]
  home = ["HTML", "LLM"]